name: adoptium-build

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: write

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    name: "java-docker-images:adoptium_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - 8
          - 11
          - 17
          - 19
          - 21
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta_adoptium
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/en0tuk/adoptium
          tags: |
            ${{ matrix.tag }}
            
      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Adoptium/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_adoptium.outputs.tags }}
          labels: ${{ steps.meta_adoptium.outputs.labels }}

  build-alpine:
    if: contains(github.ref, 'alpine')
    name: "java-docker-images:adoptium_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - 8-alpine
          - 11-alpine
          - 17-alpine
          - 19-alpine
          - 21-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta_adoptium
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/en0tuk/adoptium
          tags: |
            ${{ matrix.tag }}
            
      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Adoptium/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_adoptium.outputs.tags }}
          labels: ${{ steps.meta_adoptium.outputs.labels }}