name: azul-zulu-build

on: workflow_dispatch

jobs:
  java-docker-images:
    name: "java-docker-images:zulu_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - 8
          - 11
          - 17
          - 21
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta_azulzulu
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/vega-network/azul-zulu
          tags: |
            ${{ matrix.tag }}
            
      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Azul Zulu/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_azulzulu.outputs.tags }}
          labels: ${{ steps.meta_azulzulu.outputs.labels }}
