name: task-graalvmb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  java-docker-images:
    name: "java-docker-images:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - 11
          - 17
          - 19
          - 21
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta_graalvm
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/vovamod/java-docker-images
          tags: |
            type=raw,${{ matrix.tag }}
            
      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: ./GraalVM/${{ matrix.tag }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_graalvm.outputs.tags }}
          labels: ${{ steps.meta_graalvm.outputs.labels }}
